### ISSUE TITLE
Avoid exporting fe80::/64

### ISSUE THREAD

**Issue by sts** [saz/puppet-ssh#218]
Currently setting `ssh::hostkeys::export_ipaddresses: true` exports all v4 and v6 ip addresses 
discovered by `Puppet::Parser::Functions#ipaddresses`. With v6, interfaces are automatically assigned an address from the link-local prefix `fe80::/64 (fe80:0:0:0:0:0:0:0 - fe80:0:0:0:ffff:ffff:ffff:ffff)`

Link-local addresses are only valid and unique for a single link. Its usually generated by appending the mac address as the least significant 64 bits. There are two issues with that:

- There are conditions where the same link-local address is used for multiple interfaces (bonding, bridges), which leads to duplicate address entries in the array returned by the `ipaddresses` function. Although this is more a cosmetic issue, calling `uniq` before returning the result would be great.

- Not sure whether there is a real use case to configure SSH for link-local v6 addresses via Puppet and `fe80::/64` could be removed entirely from the results.

**Comment by saz** [comment]
If you're willing to send in a PR, I'll be more than happy to merge it.

**Comment by sts** [comment]
@saz any news on this?

**Comment by lesinigo** [comment]
Another issue with exporting `fe80::/64` addresses is that they get to change pretty frequently if you happen to have hosts running docker containers: with its default networking a new `veth` pair will be created every time you start a container. You end up with all your Puppet-managed nodes always collecting changes to `Sshkey` resources because the list of docker hosts IPv6 aliases keeps changing.

As an example I get a lot of these, on every node, at every agent run, because we have containers constantly coming and going (blanks added for clarity):
```
Notice: /Stage[main]/Ssh::Knownhosts/Sshkey[docker1.foobar_dsa]/host_aliases:
current_value ['docker1.foobar', 'docker1', '172.17.0.1', '192.168.100.1', 'fe80::250:56ff:fe95:c404', 'fe80::42:9cff:fe10:8be4', 'fe80::3ca8:74ff:fefd:8e29', 'fe80::5410:6aff:fee5:157b', 'fe80::549d:4cff:fe1d:7004'],
    should be ['docker1.foobar', 'docker1', '172.17.0.1', '192.168.100.1', 'fe80::250:56ff:fe95:c404', 'fe80::42:3fff:fec3:c410', 'fe80::b88c:b1ff:fe85:9083', 'fe80::6861:a0ff:feac:e720', 'fe80::f40c:cfff:fee4:b94b'] (noop)
```


This is partly a cosmetic issue but partly annoying on the practical side if you rely on any kind of reporting on your node resources (eg. Puppetexplorer / Puppetboard) because they will never be in the "everything applied, nothing to do" status.

So this is a big +1 for merging the proposed PR and possibly pushing a new release on the forge with the latest commits and fixes already in master.
