### ISSUE TITLE
please add a new tag/release for concat/stdlib 5.x support

### ISSUE THREAD

**Issue by aba-rechsteiner** [saz/puppet-ssh#264]

**Comment by slauger** [comment]
@saz any update here?

**Comment by aba-rechsteiner** [comment]
the same here https://github.com/saz/puppet-sudo/pull/230

**Comment by saz** [comment]
Would be great, if you can give me some feedback on the current master of this module, if you're running into issues.

Note: due to #267 this might break some setups (e.g. if there is a load balancer in use, as an ip address is configured on the load balancer and not on the "target" system).

**Comment by slauger** [comment]
The fix #267 works for me and i see that all my secondary ips are now added to my known_hosts files.  No issues so far. 
```
Notice: /Stage[main]/Ssh::Knownhosts/Sshkey[node01.example.com_ed25519]/host_aliases: current_value 
['node01.example.com', 'node01', '192.168.161.20', 'aaaa:bbbb:cccc:3153::2', '192.168.161.20', 'aaaa:bbbb:cccc:3153::2'],
  should be
['node01.example.com', 'node01', '192.168.161.20', '192.168.147.145', 'aaaa:bbbb:cccc:3153::2'] (noop)
```
I never missed those ips because i only run ssh on the primary ip address. All interfaces with floating ips are excluded via `ssh::hostkeys::exclude_interfaces`. 

Why not adding a new parameter to `ssh::hostkeys` to enable/disable the new behaviour (e.g. `ssh::hostkeys::secondary_ips`)? This would avoid any breakage in setups with virtual/cluster ips.

**Comment by saz** [comment]
As the next release is a major release anyways, I'd rather break it now.
Implementing old and new behavior will require maintenance of both versions and it's in fact a bug, that there where addresses missing.

Thanks for the feedback!

**Comment by aba-rechsteiner** [comment]
I only use the basic functions of this module, but I could not find any issues.
